# Generated by Django 3.2.6 on 2021-08-07 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=2)),
                ('street', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, default='SN', max_length=50, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
